import { observable, action, computed } from 'mobx';
import { setupMaster } from 'cluster';

class Store {
    @observable personas: any[] = [
        {
            Nombre: "Carolina Escobar",
            Pimenton: 0,
            Cebolla: 8,
            Champinon: 10,
            Tomate: 5,
            Queso: 10,
            Pina: 6,
            Maduro: 6,
            Maiz: 9,
            Jamon: 6,
            Pollo: 10,
            Tocineta: 10,
            Aceitunas: 0,
            Anchoas: 0,
            Pepperoni: 7,
            Salami: 7,
            Jalapenos: 0,
            JamonSerrano: 10,
            Chorizo: 10,
            Albahaca: 0,
            Carne: 0,
            Oregano: 3,
            Rugula: 0,
            Cabano: 5,
            Berenjena: 0,
            Mariscos: 0
        },
        {
            Nombre: "Cristian Rodríguez",
            Pimenton: 5,
            Cebolla: 8,
            Champinon: 9,
            Tomate: 7,
            Queso: 10,
            Pina: 10,
            Maduro: 7,
            Maiz: 1,
            Jamon: 6,
            Pollo: 5,
            Tocineta: 5,
            Aceitunas: 8,
            Anchoas: 6,
            Pepperoni: 10,
            Salami: 10,
            Jalapenos: 0,
            JamonSerrano: 8,
            Chorizo: 2,
            Albahaca: 7,
            Carne: 9,
            Oregano: 9,
            Rugula: 0,
            Cabano: 8,
            Berenjena: 3,
            Mariscos: 1
        },
        {
            Nombre: "Luis Felipe Vergara",
            Pimenton: 6,
            Cebolla: 8,
            Champinon: 10,
            Tomate: 9,
            Queso: 9,
            Pina: 0,
            Maduro: 1,
            Maiz: 1,
            Jamon: 7,
            Pollo: 7,
            Tocineta: 8,
            Aceitunas: 4,
            Anchoas: 2,
            Pepperoni: 10,
            Salami: 10,
            Jalapenos: 10,
            JamonSerrano: 8,
            Chorizo: 7,
            Albahaca: 9,
            Carne: 10,
            Oregano: 9,
            Rugula: 9,
            Cabano: 8,
            Berenjena: 8,
            Mariscos: 7
        },
        {
            Nombre: "Ilian Londono",
            Pimenton: 10,
            Cebolla: 10,
            Champinon: 10,
            Tomate: 3,
            Queso: 10,
            Pina: 0,
            Maduro: 2,
            Maiz: 8,
            Jamon: 10,
            Pollo: 8,
            Tocineta: 8,
            Aceitunas: 4,
            Anchoas: 0,
            Pepperoni: 8,
            Salami: 8,
            Jalapenos: 5,
            JamonSerrano: 5,
            Chorizo: 7,
            Albahaca: 8,
            Carne: 6,
            Oregano: 10,
            Rugula: 6,
            Cabano: 7,
            Berenjena: 3,
            Mariscos: 3
        },
        {
            Nombre: "Jose Ossa",
            Pimenton: 5,
            Cebolla: 6,
            Champinon: 10,
            Tomate: 8,
            Queso: 10,
            Pina: 8,
            Maduro: 7,
            Maiz: 6,
            Jamon: 10,
            Pollo: 10,
            Tocineta: 10,
            Aceitunas: 9,
            Anchoas: 5,
            Pepperoni: 6,
            Salami: 5,
            Jalapenos: 0,
            JamonSerrano: 9,
            Chorizo: 10,
            Albahaca: 10,
            Carne: 10,
            Oregano: 10,
            Rugula: 3,
            Cabano: 1,
            Berenjena: 0,
            Mariscos: 0
        },
        {
            Nombre: "Juan Antonio Pazmino",
            Pimenton: 10,
            Cebolla: 10,
            Champinon: 5,
            Tomate: 10,
            Queso: 10,
            Pina: 8,
            Maduro: 10,
            Maiz: 10,
            Jamon: 10,
            Pollo: 10,
            Tocineta: 10,
            Aceitunas: 0,
            Anchoas: 0,
            Pepperoni: 10,
            Salami: 7,
            Jalapenos: 7,
            JamonSerrano: 10,
            Chorizo: 10,
            Albahaca: 10,
            Carne: 8,
            Oregano: 10,
            Rugula: 8,
            Cabano: 9,
            Berenjena: 3,
            Mariscos: 3
        },
        {
            Nombre: "Mateo Zuluaga",
            Pimenton: 5,
            Cebolla: 5,
            Champinon: 8,
            Tomate: 9,
            Queso: 10,
            Pina: 6,
            Maduro: 6,
            Maiz: 8,
            Jamon: 8,
            Pollo: 6,
            Tocineta: 8,
            Aceitunas: 2,
            Anchoas: 2,
            Pepperoni: 8,
            Salami: 5,
            Jalapenos: 5,
            JamonSerrano: 2,
            Chorizo: 2,
            Albahaca: 4,
            Carne: 2,
            Oregano: 7,
            Rugula: 7,
            Cabano: 5,
            Berenjena: 3,
            Mariscos: 9
        },
        {
            Nombre: "Oscar Hoyos",
            Pimenton: 2,
            Cebolla: 9,
            Champinon: 5,
            Tomate: 10,
            Queso: 10,
            Pina: 1,
            Maduro: 2,
            Maiz: 0,
            Jamon: 8,
            Pollo: 7,
            Tocineta: 10,
            Aceitunas: 0,
            Anchoas: 0,
            Pepperoni: 9,
            Salami: 8,
            Jalapenos: 2,
            JamonSerrano: 7,
            Chorizo: 9,
            Albahaca: 1,
            Carne: 9,
            Oregano: 5,
            Rugula: 0,
            Cabano: 3,
            Berenjena: 0,
            Mariscos: 0
        },
        {
            Nombre: "Paula García",
            Pimenton: 9,
            Cebolla: 9,
            Champinon: 10,
            Tomate: 10,
            Queso: 9,
            Pina: 8,
            Maduro: 7,
            Maiz: 8,
            Jamon: 7,
            Pollo: 8,
            Tocineta: 8,
            Aceitunas: 2,
            Anchoas: 0,
            Pepperoni: 9,
            Salami: 7,
            Jalapenos: 3,
            JamonSerrano: 7,
            Chorizo: 7,
            Albahaca: 8,
            Carne: 0,
            Oregano: 10,
            Rugula: 8,
            Cabano: 0,
            Berenjena: 10,
            Mariscos: 0
        },
        {
            Nombre: "Paulo Rosas",
            Pimenton: 7,
            Cebolla: 8,
            Champinon: 9,
            Tomate: 6,
            Queso: 9,
            Pina: 5,
            Maduro: 6,
            Maiz: 6,
            Jamon: 5,
            Pollo: 10,
            Tocineta: 10,
            Aceitunas: 10,
            Anchoas: 2,
            Pepperoni: 10,
            Salami: 10,
            Jalapenos: 10,
            JamonSerrano: 10,
            Chorizo: 7,
            Albahaca: 5,
            Carne: 2,
            Oregano: 10,
            Rugula: 6,
            Cabano: 9,
            Berenjena: 0,
            Mariscos: 10
        },
        {
            Nombre: "Santiago Mondragon",
            Pimenton: 5,
            Cebolla: 8,
            Champinon: 9,
            Tomate: 8,
            Queso: 10,
            Pina: 0,
            Maduro: 8,
            Maiz: 7,
            Jamon: 8,
            Pollo: 9,
            Tocineta: 10,
            Aceitunas: 5,
            Anchoas: 0,
            Pepperoni: 10,
            Salami: 10,
            Jalapenos: 8,
            JamonSerrano: 10,
            Chorizo: 10,
            Albahaca: 10,
            Carne: 8,
            Oregano: 10,
            Rugula: 10,
            Cabano: 8,
            Berenjena: 5,
            Mariscos: 2
        },
        {
            Nombre: "Santiago Ortiz Guevara",
            Pimenton: 4,
            Cebolla: 4,
            Champinon: 9,
            Tomate: 5,
            Queso: 10,
            Pina: 2,
            Maduro: 3,
            Maiz: 2,
            Jamon: 5,
            Pollo: 8,
            Tocineta: 8,
            Aceitunas: 0,
            Anchoas: 0,
            Pepperoni: 10,
            Salami: 6,
            Jalapenos: 0,
            JamonSerrano: 4,
            Chorizo: 0,
            Albahaca: 0,
            Carne: 5,
            Oregano: 5,
            Rugula: 0,
            Cabano: 5,
            Berenjena: 0,
            Mariscos: 0
        },
        {
            Nombre: "Sebastián Restrepo",
            Pimenton: 10,
            Cebolla: 10,
            Champinon: 10,
            Tomate: 7,
            Queso: 2,
            Pina: 6,
            Maduro: 6,
            Maiz: 4,
            Jamon: 4,
            Pollo: 10,
            Tocineta: 8,
            Aceitunas: 0,
            Anchoas: 0,
            Pepperoni: 10,
            Salami: 8,
            Jalapenos: 0,
            JamonSerrano: 3,
            Chorizo: 3,
            Albahaca: 5,
            Carne: 7,
            Oregano: 9,
            Rugula: 0,
            Cabano: 0,
            Berenjena: 7,
            Mariscos: 7
        },
        {
            Nombre: "Estefanía Montana Buitrago",
            Pimenton: 8,
            Cebolla: 8,
            Champinon: 10,
            Tomate: 10,
            Queso: 10,
            Pina: 8,
            Maduro: 4,
            Maiz: 4,
            Jamon: 7,
            Pollo: 6,
            Tocineta: 9,
            Aceitunas: 0,
            Anchoas: 0,
            Pepperoni: 9,
            Salami: 9,
            Jalapenos: 7,
            JamonSerrano: 7,
            Chorizo: 6,
            Albahaca: 0,
            Carne: 4,
            Oregano: 10,
            Rugula: 2,
            Cabano: 5,
            Berenjena: 7,
            Mariscos: 6
        }
    ]
    
    @observable personaUno: any = {
        Nombre: "-",
        Pimenton:0,
        Cebolla:0,
        Champinon: 0,
        Tomate:0,
        Queso: 0,
        Pina:0,
        Maduro:0,
        Maiz:0,
        Jamon:0,
        Pollo: 0,
        Tocineta: 0,
        Aceitunas:0,
        Anchoas:0,
        Pepperoni:0,
        Salami:0,
        Jalapenos:0,
        JamonSerrano: 0,
        Chorizo: 0,
        Albahaca:0,
        Carne:0,
        Oregano:0,
        Rugula:0,
        Cabano:0,
        Berenjena:0,
        Mariscos: 0
    }
    @observable personaDos: any = {};
    @observable resultado: any[] = [];

    @action setPersonaUno(nombre: string) {
        this.personas.forEach(element => {
            if (element.Nombre == nombre) {
                let string = JSON.stringify(element)
                this.personaUno = [];
                this.personaUno = JSON.parse(string);
                console.log(JSON.parse(string))
            }
        });
    }

}

export const store = new Store();